# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bird < Formula
  desc "Bird CLI — operate the Bird platform from the terminal"
  homepage "https://bird.com/cli"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.platform.bird.com/releases/v0.5.2/bird-darwin-amd64.tar.gz"
      sha256 "5805fe4063ef98fd557841cbe6f58862cfec16e1f2f5e765c9e50acf3cd39dc0"

      define_method(:install) do
        bin.install "bird"
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.platform.bird.com/releases/v0.5.2/bird-darwin-arm64.tar.gz"
      sha256 "67e0f7683fd2dbf2637d7ef59b9dd309f2ca9c9922cc99e322686e9f4a07cb27"

      define_method(:install) do
        bin.install "bird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.platform.bird.com/releases/v0.5.2/bird-linux-amd64.tar.gz"
      sha256 "c126ee1e68b556f7aa317965c9a127fecb8b742813aa605e5711def42350debd"
      define_method(:install) do
        bin.install "bird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.platform.bird.com/releases/v0.5.2/bird-linux-arm64.tar.gz"
      sha256 "173389190312fd36f2b2dbec70a9903deefb2e3eee49b1c923f08e956177222a"
      define_method(:install) do
        bin.install "bird"
      end
    end
  end

  def caveats
    <<~EOS
      Authenticate before use:
        bird auth login
    EOS
  end

  test do
    system "#{bin}/bird", "--version"
  end
end
